# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
usePassword: false
cluster:
  enabled: false
master:
  persistence:
    size: 2Gi
    enabled: true
  nodeSelector:
    kubernetes.io/os: linux
replica:
  persistence:
    size: 2Gi
    enabled: true
  nodeSelector:
    kubernetes.io/os: linux

volumePermissions:
  enabled: true
